# Generated by Django 5.1.3 on 2024-11-06 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress'},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='last_accessed',
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.module'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
