# Generated by Django 5.1.3 on 2024-11-06 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_progress_options_remove_progress_last_accessed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['module__order']},
        ),
        migrations.AddField(
            model_name='progress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='app.module'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
